import type { AiClient, AiTurn, AiTool } from './types';

const MODEL = 'gemini-2.5-flash';

/**
 * ⚠️ Development-only client.
 *
 * This calls Google's API directly from the browser with a key the person
 * pastes into Settings themselves — the same limitation the original
 * LifeAssist prototype had. It's fine for local/personal use on a device
 * only you control, but the key IS visible in network requests and browser
 * storage, so it must never be used in a deployed multi-user build.
 *
 * Phase 3 of the roadmap replaces this with a Firebase/Supabase Edge
 * Function that holds the key server-side; the AiClient interface this
 * implements stays the same, so no UI code changes when that swap happens.
 */
export class GeminiDevClient implements AiClient {
  label = 'Gemini · local dev key';

  constructor(private apiKey: string) {}

  isConfigured() {
    return this.apiKey.trim().length > 0;
  }

  async send(history: AiTurn[], prompt: string, tools?: AiTool[]): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error('No API key set.');
    }

    // Map history to Gemini API format
    const contents: any[] = history.map((turn) => ({
      role: turn.role === 'user' ? 'user' : 'model',
      parts: [{ text: turn.text }],
    }));

    // Add current user prompt
    contents.push({
      role: 'user',
      parts: [{ text: prompt }],
    });

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${this.apiKey}`;

    const systemInstruction = {
      parts: [{
        text: `You are Jelly, a responsive, highly intelligent AI personal assistant. 
Adorn a calm, articulate, slightly witty, friendly, and helpful persona. 
You have access to tools to manage the user's tasks, schedule goals, calendars, habits, and reminders. 

CRITICAL: Keep your final verbal text response extremely brief, concise, and direct (no more than 2-3 sentences maximum). Fulfill requests (like weekly roadmaps, goals, or tasks) by executing the tools to create actual tasks, goals, and calendar events. Then, provide a short 1-2 sentence confirmation of what was created without writing out long lists or paragraphs in the final text response.`
      }]
    };

    let loopCount = 0;
    const maxLoops = 8; // safeguard against infinite loops

    while (loopCount < maxLoops) {
      let requestBody: any = { 
        contents,
        systemInstruction
      };
      
      if (tools && tools.length > 0) {
        requestBody.tools = [
          {
            functionDeclarations: tools.map(t => ({
              name: t.name,
              description: t.description,
              parameters: t.parameters,
            }))
          }
        ];
      }

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API error (${response.status}): ${errorText}. Check the key in Settings.`);
      }

      const result = await response.json();
      const candidate = result?.candidates?.[0];
      const content = candidate?.content;
      const parts = content?.parts;

      if (!content || !parts || parts.length === 0) {
        throw new Error('The assistant returned an empty response. Try rephrasing.');
      }

      // Check if the model requested function calls
      const functionCalls = parts.filter((p: any) => p.functionCall);

      if (functionCalls.length > 0) {
        // 1. Add model's functionCall message to contents history
        contents.push(content);

        // 2. Execute all requested tool calls in parallel or sequence
        const responseParts: any[] = [];
        for (const part of functionCalls) {
          const call = part.functionCall;
          const tool = tools?.find(t => t.name === call.name);
          let output = '';
          if (tool) {
            try {
              output = await tool.execute(call.args);
            } catch (err: any) {
               output = `Error executing tool: ${err.message || err}`;
            }
          } else {
            output = `Error: Tool "${call.name}" not found.`;
          }
          responseParts.push({
            functionResponse: {
              name: call.name,
              response: { output }
            }
          });
        }

        // 3. Add function responses to history
        contents.push({
          role: 'function',
          parts: responseParts
        });

        loopCount++;
      } else {
        // Return final text response generated by the model
        const text = parts.map((p: any) => p.text).filter(Boolean).join('\n');
        if (!text) {
          throw new Error('Empty text content received from assistant.');
        }
        return text;
      }
    }

    throw new Error('Exceeded maximum tool execution turns.');
  }
}
